apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: kafka
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=A custom OpenShift kafka profile
      include=openshift-node
      [cpu]
      force_latency=${force_latency}
      min_perf_pct=${min_perf_pct}
      [scheduler]
      sched_min_granularity_ns=${sched_min_granularity_ns}
      sched_wakeup_granularity_ns=${sched_wakeup_granularity_ns}
      sched_migration_cost_ns=${sched_migration_cost_ns}
      [disk]
      elevator=${elevator}
      readahead=${readahead}
      [net]
      txqueuelen=${txqueuelen}
      [sysctl]
      vm.dirty_background_bytes=${dirty_background_bytes}
      vm.dirty_bytes=${dirty_bytes}
      vm.dirty_expire_centisecs=${dirty_expire_centisecs}
      vm.dirty_writeback_centisecs=${dirty_writeback_centisecs}
      vm.min_free_kbytes=${min_free_kbytes} 
      net.ipv4.tcp_ecn=${tcp_ecn}
      net.core.busy_read=${busy_read}
      net.core.busy_poll=${busy_poll}
      net.core.rmem_default=${mem_default}
      net.core.wmem_default=${mem_default}
      net.core.rmem_max=${mem_max}
      net.core.wmem_max=${mem_max}
      net.ipv4.tcp_rmem="4096 ${tcp_def} ${mem_max}"
      net.ipv4.tcp_wmem="4096 ${tcp_def} ${mem_max}"
      net.ipv4.tcp_max_syn_backlog=${tcp_max_syn_backlog}
      net.core.netdev_max_backlog=${netdev_max_backlog}
      net.core.somaxconn=${somaxconn}
      net.ipv4.tcp_fin_timeout=${tcp_fin_timeout}
      net.ipv4.tcp_limit_output_bytes=${tcp_limit_output_bytes}
      net.ipv4.tcp_max_tw_buckets=${tcp_max_tw_buckets}
      net.core.optmem_max=${optmem_max}
      net.ipv4.ipfrag_low_thresh=${ipfrag_low_thresh}
      net.ipv4.tcp_low_latency=${tcp_low_latency}
      net.ipv4.tcp_tw_reuse=${tcp_tw_reuse}
      net.ipv4.tcp_no_metrics_save=${tcp_no_metrics_save}
      net.ipv4.tcp_timestamps=${tcp_timestamps}
      net.ipv4.tcp_max_orphans=${tcp_max_orphans}
      net.ipv4.ipfrag_low_thresh=${ipfrag_low_thresh}
      net.ipv4.tcp_low_latency=${tcp_low_latency}
      net.ipv4.tcp_tw_reuse=${tcp_tw_reuse}
      net.ipv4.tcp_no_metrics_save=${tcp_no_metrics_save}
      net.ipv4.tcp_timestamps=${tcp_timestamps}
      net.ipv4.tcp_max_orphans=${tcp_max_orphans}
      net.ipv4.tcp_synack_retries=${tcp_synack_retries}
      net.ipv4.tcp_retries2=${tcp_retries2}
      net.ipv4.tcp_keepalive_probes=${tcp_keepalive_probes}
      net.ipv4.tcp_keepalive_intvl=${tcp_keepalive_intvl}
      net.ipv4.tcp_keepalive_time=${tcp_keepalive_time}
      net.ipv4.tcp_congestion_control=${tcp_congestion_control}
    name: openshift-kafka
  recommend:
  - match:
    - label: olm.catalogSource
      value: addon-operator-catalog
      type: pod
      match:
      - label: node.kubernetes.io/instance-type
        value: m5a.xlarge
      match:
    priority: 10    	
    profile: openshift-kafka
